id: I4103B822
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T07:57:45+00:00'
last_modified: '2022-06-08T09:13:49.573471+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17141
  title: ན་བཟའ་བེའུ་བུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedSealed
  restrictedInChina: false
  base:
    CCA2:
      image_group_id: I8LS17153
      title: ''
      total_pages: 348
      order: 1
      base_file: CCA2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
